name: mdk_app_theme
description: "MDK 공용 ThemeData/토큰/컨트롤러 패키지"
publish_to: "none"
version: 0.2.0

environment:
  sdk: '>=3.6.0 <4.0.0'
  flutter: ">=3.27.0"

dependencies:
  flutter:
    sdk: flutter
  adaptive_theme: ^3.7.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  custom_lint: ^0.8.0
  riverpod_lint: ^3.0.3
  build_runner: ^2.7.1
  lints: ^2.1.1
  flutter_riverpod: ^3.0.3

flutter:
  uses-material-design: false
  assets:
    - assets/font/PretendardVariable.ttf
  fonts:
    - family: Pretendard Variable
      fonts:
        - asset: assets/font/PretendardVariable.ttf
          weight: 400
    - family: Paperlogy
      fonts:
        - asset: assets/font/paperlogy/Paperlogy-1Thin.ttf
          weight: 100
        - asset: assets/font/paperlogy/Paperlogy-2ExtraLight.ttf
          weight: 200
        - asset: assets/font/paperlogy/Paperlogy-3Light.ttf
          weight: 300
        - asset: assets/font/paperlogy/Paperlogy-4Regular.ttf
          weight: 400
        - asset: assets/font/paperlogy/Paperlogy-5Medium.ttf
          weight: 500
        - asset: assets/font/paperlogy/Paperlogy-6SemiBold.ttf
          weight: 600
        - asset: assets/font/paperlogy/Paperlogy-7Bold.ttf
          weight: 700
        - asset: assets/font/paperlogy/Paperlogy-8ExtraBold.ttf
          weight: 800
        - asset: assets/font/paperlogy/Paperlogy-9Black.ttf
          weight: 900
